build:
	go build ./...

test:
	go test ./...

run:
	go run main.go

# The go mod tidy command adds missing module requirements for imported packages and removes requirements on modules that aren't used anymore.
install:
	go install
	go mod tidy
